---
- name: Reboot all Docker Swarm services
  hosts: all
  gather_facts: no
  tasks:
    - name: Ensure Docker Swarm is initialized
      community.docker.docker_swarm:
        state: present

    - name: Get list of services in the Docker Swarm
      community.docker.docker_service_info:
        register: docker_services

    - name: Reboot Docker Swarm services
      community.docker.docker_service:
        name: "{{ item.Name }}"
        state: restarted
      loop: "{{ docker_services.services }}"
