---
- name: Reset Docker Swarm cluster
  hosts: all
  gather_facts: yes
  become: true

  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure Docker Swarm is initialized
      community.docker.docker_swarm:
        state: present

    - name: Get list of services in the Docker Swarm
      community.docker.docker_service_info:
      register: docker_services

    - name: Remove Docker Swarm services
      community.docker.docker_service:
        name: "{{ item.Name }}"
        state: absent
      loop: "{{ docker_services.services }}"

    - name: Leave Docker Swarm
      community.docker.docker_swarm:
        state: absent
