name: Docker Swarm Solution CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-and-test:
    runs-on: ubuntu-latest

    env:
      ANSIBLE_HOST_KEY_CHECKING: false
      ANSIBLE_STDOUT_CALLBACK: yaml

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y vagrant virtualbox ansible

      # Install Vagrant plugins for VirtualBox compatibility
      - name: Install Vagrant plugins
        run: |
          vagrant plugin install vagrant-vbguest
          vagrant plugin install vagrant-disksize

      # Start Vagrant environment
      - name: Start Vagrant environment
        run: |
          vagrant up --provider=virtualbox --provision

      # Check the status of Docker nodes on the master node
      - name: Verify Docker Swarm setup
        run: |
          vagrant ssh master1 -c "docker node ls"

      # Run tests
      - name: Run Docker Swarm master tests
        run: |
          vagrant ssh master1 -c "docker service ls"
          vagrant ssh master1 -c "docker node ls"
      
      - name: Run Docker Swarm worker tests
        run: |
          vagrant ssh worker1 -c "docker --version"

      # Tear down Vagrant environment after tests
      - name: Destroy Vagrant environment
        if: always()
        run: |
          vagrant destroy -f
